= Teo Wei Zheng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Concierge(TM)

---

== Overview

Concierge(TM) is a desktop application simulating a hotel management system used by hotel
owners and receptionists. The user interacts with it using a CLI, and it has a GUI created
with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=teowz46[Code Contributed]]

* *Major enhancement*: Implemented the entire `service` architecture and command

** What it does: The `service` command allows for the integration of all the hotel's goods
   and services into Concierge(TM). Users will be able to use Concierge(TM) to charge and
   keep track of the expenditure of all guests on the hotel's goods and services.

** Justification: A hotel often provides many different kinds of goods and services, such as
   room service, restaurants, minibar, swimming pool, etc. Since all of these goods and
   services belong to the hotel, there should be a centralised system to keep track of all
   the expenditure on the hotel's goods and services, such that the expenses can be compiled
   and presented to the guest conveniently during checkout.

** Highlights: This functionality required the implementation of several different classes
   to serve as the architecture. Firstly, `Expenses` and `Expense` were required to hold the
   information regarding the `Room`'s total expenditure and each individual expenditure
   respectively. Secondly, a `Menu` of `ExpenseType` objects were required to serve as the
   main reference of all the items that are sold in the hotel. This serves as the catalogue
   for the hotel. Finally, a `Money` class was created to handle monetary values. In addition,
   the information in all of these classes need to be stored in XML, and therefore implementing
   this required significant effort to convert each class into an `XmlAdaptedClass` and to
   handle all the possible errors that can be introduced by modifying the values in the XML.
   Testing also required significant effort in adding several new test files and implementing
   several new utility methods, besides writing tests for all the classes mentioned above.

* *Minor enhancement*: added a GUI panel that displays the expenditure details of every room.

* *Other contributions*:

** Refactoring:
*** Replaced all instances and variants of "Address Book" with "Concierge".

** Documentation:
*** Modified the existing Model UML diagram with our architecture: https://github.com/CS2103-AY1819S1-F11-2/main/pull/247[#247]
*** Updated user stories in developer guide, made basic changes to the website: https://github.com/CS2103-AY1819S1-F11-2/main/pull/45[#45]

** Community:
*** PRs reviewed (with non-trivial review comments):
    https://github.com/CS2103-AY1819S1-F11-2/main/pull/90[#90],
    https://github.com/CS2103-AY1819S1-F11-2/main/pull/169[#169]
*** Reported bugs and suggestions for other teams in the class (examples:
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/130[1],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/137[2],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/139[3],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/147[4],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/153[5],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/157[6],
    https://github.com/CS2103-AY1819S1-T13-1/main/issues/158[7], )

** Tools:
*** Integrated Travis CI to the project.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
* Links to relevant sections in User Guide (for viewing on Github)
** https://github.com/CS2103-AY1819S1-F11-2/main/blob/master/docs/UserGuide.adoc#provide-room-service-code-service-code-span-class-image-img-src-images-icon-key-png-alt-icon-key-width-32-span[`service` command]

include::../UserGuide.adoc[tag=service]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
* Links to relevant sections in Developer Guide (for viewing on Github)
** https://github.com/CS2103-AY1819S1-F11-2/main/blob/master/docs/DeveloperGuide.adoc#expense-expenses-and-expensetype[Expense, Expenses, and ExpenseType]
** https://github.com/CS2103-AY1819S1-F11-2/main/blob/master/docs/DeveloperGuide.adoc#money[Money]
** https://github.com/CS2103-AY1819S1-F11-2/main/blob/master/docs/DeveloperGuide.adoc#servicecommand[ServiceCommand]


include::../DeveloperGuide.adoc[tag=expenses]

include::../DeveloperGuide.adoc[tag=money]

include::../DeveloperGuide.adoc[tag=service]

